import '../assets/globals.css';
import { yekan } from 'src/assets/fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={yekan.variable}>
      <body>{children}</body>
    </html>
  );
}
