import '@/assets/globals.css';
import { yekan } from '@/assets/fonts';
import Layout from '@/components/layouts/Layout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={yekan.variable}>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
